export const SET_PRODUCTS="SET_PRODUCTS";
export const SELECTED_PRODUCT="SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT="REMOVE_SELECTED_PRODUCT";
export const GET_PRODUCT="GET_PRODUCT";
export const INSERT_CART="INSERT_CART";



export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';