export const ActionTypes={
SET_PRODUCTS:"SET_PRODUCTS",
SELECTED_PRODUCT:"SELECTED_PRODUCT",
REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
GET_PRODUCT:"GET_PRODUCT",
INSERT_CART:"INSERT_CART",


};